apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"dev-sa","namespace":"dev"}}
  creationTimestamp: "2026-02-27T07:19:50Z"
  name: dev-sa
  namespace: dev
  resourceVersion: "15941"
  uid: ebaa6569-bd6a-4170-89ab-57ec4a39cdcd
